
name: Framework

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
        
      - name: Remove temporary directory with retry
        run: |
          echo "Attempting to remove directory..."
          tryCount=0
          maxRetries=5
          dir="E:\\GitHub Runner\\actions-runner-win-x64-2.321.0\\_work\\_temp\\71440b1f-43fb-4a98-af38-16ef9796e5ac"
          until rmdir /s /q "$dir" || [ $tryCount -eq $maxRetries ]; do
            echo "Retrying to remove the directory..."
            tryCount=$((tryCount + 1))
            sleep 1
          done
        continue-on-error: true 

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2

     # - name: Setup .NET (includes NuGet)
     #   uses: actions/setup-dotnet@v3
      #  with:
       #   dotnet-version: '6.0'

      - name: Navigate To Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Crearte Build Directory
        run: mkdir _build

      - name: Restore Packages
        run: nuget restore WebApplication1.sln

      - name: Build Solution
        run: |
          msbuild.exe WebApplication1.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=fileSystem /p:DeleteExistingFiles=true /p:Platform="Any CPU" /p:Configuration="Release" /p:PublishUrl="../_build"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DemoBuild
          path: "${{ github.workspace }}\_build"
        
