
name: Framework

on:
  push:
    branches: [ "master" ]
    

jobs:
  build:
    runs-on: self-hosted
    # defaults:
    #   run:
    #     working-directory: ./FrameWork/FrameWork
    
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2
        
     
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
          
     # - name: Setup .NET (includes NuGet)
     #   uses: actions/setup-dotnet@v3
      #  with:
       #   dotnet-version: '6.0'

      - name: Navigate To Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Crearte Build Directory
        run: mkdir _build

      - name: Restore Packages
        run: nuget restore WebApplication1.sln

      - name: Build Solution
        run: |
          msbuild.exe WebApplication1.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=fileSystem /p:DeleteExistingFiles=true /p:Platform="Any CPU" /p:Configuration="Release" /p:PublishUrl="../_build"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DemoBuild
          path: "${{ github.workspace }}\_build"
        
