
name: Framework

on:
  push:
    branches: [ "master" ]
    

jobs:
  build:
    runs-on: self-hosted
    # defaults:
    #   run:
    #     working-directory: ./FrameWork/FrameWork
    
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2
        
     
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
          
      # - name: Navigate To Workspace
      #   shell: cmd
      #   run: |
      #     cd $GITHUB_WORKSPACE

      - name: Crearte Build Directory
        shell: cmd
        run: |
          mkdir out
        
      - name: Restore Packages
        shell: cmd
        run: nuget restore WebApplication1.sln

      - name: Build Solution
        shell: cmd
        run: |
          msbuild WebApplication1.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"
    
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Framework
          path: "./_build"
      
        
  deploy:
      runs-on: self-hosted # Ensure this is a valid self-hosted runner
      needs: build
      steps:
        - name: Download Artifact
          uses: actions/download-artifact@v4
          with:
            name: Framework
            path: "E:/action-runner/actions-runner-win-x64-2.322.0/_work/FrameWork/out"
      
        # - name: Deploy to IIS
        #   uses: ChristopheLav/iis-deploy@v1
        #   with:
        #     website-name: 'MyWebsite'
        #     msdeploy-service-url: ${{ secrets.MSDEPLOY_URL }}
        #     msdeploy-username: ${{ secrets.MSDEPLOY_USERNAME }}
        #     msdeploy-password: ${{ secrets.MSDEPLOY_PASSWORD }}
        #     msdeploy-skipextrafilesonserver: true
        #     source-path: E:\action-runner\actions-runner-win-x64-2.322.0\_work\FrameWork

        - name: Deploy to IIS using CMD
          shell: cmd
          run: |             
            set REMOTE_SERVER=${{ secrets.MSDEPLOY_URL }}
            set USERNAME=${{ secrets.MSDEPLOY_USERNAME }}
            set PASSWORD=${{ secrets.MSDEPLOY_PASSWORD }}
            net use E: \\%REMOTE_SERVER%\C$\inetpub\wwwroot\YourApp /user:%USERNAME% %PASSWORD%        
            xcopy /E /I /Y /H "C:\path\to\publish\*" "E:\"
            wmic /node:%REMOTE_SERVER% /user:%USERNAME% /password:%PASSWORD% service where name="W3SVC" call restartservice
            net use E: /delete
