
name: Framework

on:
  push:
    branches: [ "master" ]
    

jobs:
  build:
    runs-on: self-hosted
    # defaults:
    #   run:
    #     working-directory: ./FrameWork/FrameWork
    
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v2
        
     
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
          
      # - name: Navigate To Workspace
      #   run: cd $GITHUB_WORKSPACE

      - name: Crearte Build Directory
        shell: cmd
        run: |
          mkdir -p $GITHUB_WORKSPACE/out
        
      - name: Restore Packages
        shell: cmd
        run: nuget restore WebApplication1.sln

      - name: Build Solution
        shell: cmd
        run: |
          msbuild WebApplication1.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=fileSystem /p:DeleteExistingFiles=true /p:Platform="Any CPU" /p:Configuration="Release" /p:PublishUrl="out"
    
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DemoBuild
          path: $GITHUB_WORKSPACE/out
      
        
  deploy:
      runs-on: self-hosted  # Ensure this is a valid self-hosted runner
      needs: build
      steps:
        - name: Download Artifact
          uses: actions/download-artifact@v4
          with:
            name: DemoBuild
            path: "build"
      
        # - name: Deploy to IIS
        #   uses: ChristopheLav/iis-deploy@v1
        #   with:
        #     website-name: 'MyWebsite'
        #     msdeploy-service-url: ${{ secrets.MSDEPLOY_URL }}
        #     msdeploy-username: ${{ secrets.MSDEPLOY_USERNAME }}
        #     msdeploy-password: ${{ secrets.MSDEPLOY_PASSWORD }}
        #     msdeploy-skipextrafilesonserver: true
        #     source-path: E:\action-runner\actions-runner-win-x64-2.322.0\_work\FrameWork

        - name: Deploy to IIS using CMD
          run: |
            
            & 'C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe' -verb:sync `
            -source:contentPath="E:\action-runner\actions-runner-win-x64-2.322.0\_work\FrameWork\FrameWork\bin\Release\Publish" `
            -dest:contentPath="YourIISWebsite",computerName="${{ secrets.MSDEPLOY_URL }}e", `
              username="${{ secrets.MSDEPLOY_USERNAME }}",password="${{ secrets.MSDEPLOY_PASSWORD }}",authType="Basic" `
            -allowUntrusted
          shell: cmd
             
